"""Checks the pixel-to-metres maths, which every traffic number depends on."""

from __future__ import annotations

import numpy as np
import pytest

from traffic_flow.geometry.homography import RoadPlane
from traffic_flow.geometry.pinhole_road import (
    GroundGeometry,
    RoadCameraModel,
    fit_ground_geometry,
    fit_horizon_row,
    focal_for_target_speed,
)

HORIZON = 16.0
HEIGHT_M = 15.9
FOCAL_PX = 797.0
PRINCIPAL_COLUMN = 160.0


def _model() -> RoadCameraModel:
    geometry = GroundGeometry(
        horizon_row=HORIZON,
        camera_height_m=HEIGHT_M,
        motion_fit_quality=1.0,
        height_spread_m=0.0,
    )
    return RoadCameraModel(geometry, FOCAL_PX, PRINCIPAL_COLUMN)


def test_world_and_image_are_inverses():
    """A point pushed to metres and back must land where it started."""
    model = _model()
    points = np.array([[130.0, 100.0], [300.0, 220.0], [160.0, 150.0]])
    assert np.allclose(model.to_image(model.to_world(points)), points, atol=1e-6)


def test_depth_grows_towards_the_horizon():
    """Rows nearer the horizon are further away."""
    model = _model()
    assert model.depth_m(220.0) < model.depth_m(150.0) < model.depth_m(100.0)


def test_a_lane_is_the_same_width_at_every_distance():
    """The whole point of the projection: perspective is undone.

    Two points one lane apart must measure one lane apart in metres whether they
    are near the camera or far from it.
    """
    model = _model()
    lane_width = 3.6576
    for row in (110.0, 160.0, 210.0):
        gap_px = lane_width * (row - HORIZON) / HEIGHT_M
        pair = np.array([[160.0, row], [160.0 + gap_px, row]])
        measured = np.linalg.norm(np.diff(model.to_world(pair), axis=0))
        assert measured == pytest.approx(lane_width, rel=0.01)


def test_horizon_is_recovered_from_simulated_motion():
    """Feed the fit motion generated by a known camera; it must find that camera."""
    rng = np.random.default_rng(0)
    rows = rng.uniform(95, 230, size=8000)
    # A steady speed makes the pixel step grow with the square of the drop below
    # the horizon. Noise is added so the fit is not handed a perfect line.
    steps = 2.5e-4 * (rows - HORIZON) ** 2
    steps *= rng.normal(1.0, 0.15, size=steps.shape)

    horizon, quality = fit_horizon_row(rows, steps)
    assert horizon == pytest.approx(HORIZON, abs=4.0)
    assert quality > 0.95


def test_camera_height_comes_out_of_lane_spacing():
    rows = np.array([100.0, 140.0, 180.0, 220.0])
    gaps = 3.6576 * (rows - HORIZON) / HEIGHT_M
    geometry = fit_ground_geometry(HORIZON, 1.0, rows, gaps)
    assert geometry.camera_height_m == pytest.approx(HEIGHT_M, rel=1e-6)
    assert geometry.height_spread_m == pytest.approx(0.0, abs=1e-9)


def test_focal_scales_speed_in_proportion():
    """Doubling the focal length must double the reported speed, and no more."""
    assert focal_for_target_speed(1000.0, 50.0, 100.0) == pytest.approx(2000.0)


def test_calibration_refuses_a_sample_with_no_measured_speed():
    """NaN fails every comparison, so a plain "<= 0" check would let it through."""
    with pytest.raises(ValueError):
        focal_for_target_speed(1000.0, float("nan"), 100.0)


def test_homography_reproduces_the_camera_model():
    """The run-time homography must agree with the model it was built from."""
    model = _model()
    image_points, world_points = model.homography_pairs(rows=(95.0, 232.0), columns=(130.0, 319.0))
    plane = RoadPlane(image_points, world_points)

    probes = np.array([[150.0, 120.0], [250.0, 200.0], [200.0, 160.0]])
    assert np.allclose(plane.to_world(probes), model.to_world(probes), atol=0.05)


def test_road_plane_rejects_too_few_points():
    with pytest.raises(ValueError):
        RoadPlane(np.zeros((3, 2)), np.zeros((3, 2)))
